// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/yama-koo/ent-example/ent/group"
	"github.com/yama-koo/ent-example/ent/schema"
	"github.com/yama-koo/ent-example/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAga is the schema descriptor for aga field.
	userDescAga := userFields[0].Descriptor()
	// user.AgaValidator is a validator for the "aga" field. It is called by the builders before save.
	user.AgaValidator = userDescAga.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
}
